services:

    project:
      build:
        context: .
      
      networks:
        - project-net


    haproxy:
      image: haproxy:3.0.0-alpine
      container_name: haproxy

      networks:
        - project-net

    postgres:
      image: postgres:16.3-alpine
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: ${PG_PASSWORD}
        POSTGRES_USER: ${PG_USER}
        POSTGRES_DB: ${PG_DB}

      command: postgres -c 'config_file=/etc/postgresql/postgres.conf'

      volumes:
        - pg-data:/var/lib/postgres/data:rw
        - ./config_files/postgres.conf:/etc/postgresql/postgres.conf:ro

      networks:
        - project-net

    keydb:
      image: eqalpha/keydb:alpine_x86_64_v6.3.4 
      container_name: keydb

      networks:
        - project-net

networks:
  project-net:

volumes:
  pg-data: